//
//  APIName.swift
//  CallRecoder
//
//  Created by Varun Kumar on 11/12/20.
//  Copyright © 2020 Varun Kumar. All rights reserved.
//

import Foundation
struct APIPrefix {
    static let getconfig = "CFG"
    static let accressKey = "ACK"
    static let validateToken = "VDT"
    static let liveHomePage = "LHP"
    static let channelList = "CHL"
    static let favourite = "FAV"
    static let programGuide = "PGC"
    static let search = "SVD"
    static let regAccOtp = "RAO"
    static let signup = "REG"
    static let login = "LOG"
    static let forgetPassword = "FPO"
    static let resetPassword = "RPW"
    static let changeName = "CNA"
    static let changePassword = "CPW"
    static let changeNumber = "CMO"
    static let changeEmail = "CEM"
    static let otp = "OTP"
    static let verOtp = "VER"
    static let resendOtp = "ROT"
    static let regPasswordApi = "REG"
    static let vodSearch = "VSR"
    static let liveSearch = "LSR"
    static let channelSearch = "CSR"
    static let homePageConfig = "HPC"
    static let thematic = "TGP"
    static let vodHomePage = "VHP"
    static let group = "GRP"
    static let content = "CNT"
    static let contentDetail = "CDL"
    static let thematicSubGroupData = "TSD"
    static let genre = "GRE"
    static let contentAuthorization = "CAT"
    static let notificationMessges = "NTM"
    static let notificationRead = "NTR"
    static let csm = "CSM"
    static let fingerPrint = "FPR"
    static let deepLink = "DL"
    static let player = "PLR"
    static let activeCloak = "ACA"
    static let passCode = "PC"
    static let package = "GPL"
    static let getEligiblePackage = "GEP"
    static let deliverReceipt = "DRE"
    static let packageChannel = "PCH"
}

struct APIErrorCode {
    static let activeCloak = "203"
    static let noInternet = "101"
    static let noDataFound = "102"
    static let timeNotSync = "104"
    static let csmGeneric = "601"
    static let fingerPrint = "113"
    static let deepLink = "101"
    static let deepLinkNotification = "105"
    static let invalidSeries = "106"
    static let openExternalBrowser = "111"
    static let liveDetailIntermediateScreen = "103"
    static let serverCodeTimeNotSync = "1007"
    static let playerGeoLocation = "609"
    static let playerDeviceLimit = "608"
    static let playerSKEEntitlement = "76"
    static let playerInvalidTicket = "503"
    static let playerFairPlayItemStatus = "502"
    static let notSubscription = "801"
    static let wrongPassword = "1605"
    static let wrongPasscode = "1606"
    static let passcodeLocked = "1607"
    static let notChannelSubscription = "201"
    static let playbackTimeValidationFailedOnResume = "405"
    static let playbackTimeValidationFailedOnStartOverButton = "404" // In ios old build it is 403 and in android 404
    static let playbackTimeValidationFailedOnSeek = "403"
    static let playerCdnGeoLocation = "611"
    static let cdnErrorFor401 = "506"
    static let rrmErrorFor401 = "507"
    static let rrmErrorExcepting401_403 = "508"
}

